To enable the https://micronaut-projects.github.io/micronaut-security/snapshot/guide/index.html#refresh[Refresh Controller], you have to enable it via configuration and provide an implementation of https://micronaut-projects.github.io/micronaut-security/snapshot/api/io/micronaut/security/token/refresh/RefreshTokenPersistence.html[RefreshTokenPersistence]

Enable the refresh controller:

[source,yaml]
.src/main/resources/application.yml
----
include::{sourceDir}/src/main/resources/application.yml[tag=oauth]
----

<1> Expose `/oauth/access_token` endpoint as defined by https://tools.ietf.org/html/rfc6749#section-6[section 6 of the OAuth 2.0 spec] - Refreshing an Access Token. You will invoke this endpoint to obtain a new access token.

Create a bean of type https://micronaut-projects.github.io/micronaut-security/snapshot/api/io/micronaut/security/token/refresh/RefreshTokenPersistence.html[RefreshTokenPersistence] which leverages the Micronaut Data repository we coded in the previous section:

[source,java]
.src/main/java/example/micronaut/CustomRefreshTokenPersistence.groovy
----
include::{sourceDir}/src/main/java/example/micronaut/CustomRefreshTokenPersistence.java[]
----

<1> To register a Singleton in Micronaut’s application context annotate your class with `javax.inject.Singleton`
<2> Constructor injection of `RefreshTokenRepository`.
<3> When a new refresh token is issued, the app emits an event of type https://micronaut-projects.github.io/micronaut-security/snapshot/api/io/micronaut/security/token/event/RefreshTokenGeneratedEvent.html[RefreshTokenGeneratedEvent]. We listen to it and save it in the database.
<4> The event contains both the refresh token and the user details associated to the token.
<5> Throw an exception if the token is revoked.
<6> Return the user details associated to the refresh token. E.g. username, roles, attributes...
<7> Throw an exception if the token is not found.
