We may want to save refresh token issued by the application. For example, to be revoke a user's refresh tokens. So that a particular user can not obtain a new access token, and thus access the application's endpoints.

Persist the refresh tokens with help of https://micronaut-projects.github.io/micronaut-data/latest/guide/index.html[Micronaut Data].

> Micronaut Data is a database access toolkit that uses Ahead of Time (AoT) compilation to pre-compute queries for repository interfaces that are then executed by a thin, lightweight runtime layer.

In particular, use Micronaut JDBC

> Micronaut Data JDBC is an implementation that pre-computes native SQL queries (given a particular database dialect) and provides a repository implementation that is a simple data mapper between a JDBC ResultSet and an object.

Add the following dependencies:

[source,groovy]
.build.gradle
----
dependencies {
...
..
.
include::{sourceDir}/build.gradle[tag=micronautdata]
}
----

<1> Micronaut data is a build time tool. You need to add the build time annotation processor.
<2> Add the Micronaut Data JDBC dependency
<3> Add a JDBC driver. Add https://www.h2database.com/html/main.html[H2] driver.
<4> Add a Hikari connection pool

Create an entity to save the issued Refresh Tokens.

[source,java]
.src/main/java/example/micronaut/RefreshTokenEntity.groovy
----
include::{sourceDir}/src/main/java/example/micronaut/RefreshTokenEntity.java[tag=clazzwithoutsettersandgetters]

    // Getters and Setters
    ...
    ..
    .
}
----

<1> Specifies the entity is mapped to the database
<2> Specifies the ID of an entity
<3> Specifies that the property value is generated by the database and not included in inserts
<4> Allows assigning a data created value (such as a java.time.Instant) prior to an insert

Create a https://micronaut-projects.github.io/micronaut-data/latest/api/io/micronaut/data/repository/CrudRepository.html[CrudRepository] to include methods to peform Create, Read, Updated and Delete operations with the `RefreshTokenEntity`.


[source,java]
.src/main/java/example/micronaut/RefreshTokenRepository.groovy
----
include::{sourceDir}/src/main/java/example/micronaut/RefreshTokenRepository.java[]
----

<1>	The interface is annotated with https://micronaut-projects.github.io/micronaut-data/latest/api/io/micronaut/data/jdbc/annotation/JdbcRepository.html[@JdbcRepository] and specifies a dialect of H2 used to generate queries
<2> The CrudRepository interface take 2 generic arguments, the entity type (in this case `RefreshTokenEntity`) and the ID type (in this case Long)
<3> When a new refresh token is issued we will use this method to persist it.
<4> Before issuing a new access token, we will use this method to see if the supplied refresh token exists.
<5> We can revoke the refresh tokens of a particular user with this method.

