Access tokens expire. You can control the expiration with `micronaut.security.token.jwt.generator.access-token-expiration`. In addition to the access token, you can configure your login endpoint to also return a refresh token. You can use the refresh token to obtain a new access token.

First, add the following configuration:

[source,yaml]
.src/main/resources/application.yml
----
include::{sourceDir}/src/main/resources/application.yml[tag=refresh]
----

<1> To generate a refresh token you app must have beans of type: https://micronaut-projects.github.io/micronaut-security/snapshot/api/io/micronaut/security/token/generator/RefreshTokenGenerator.html[RefreshTokenGenerator],  https://micronaut-projects.github.io/micronaut-security/snapshot/api/io/micronaut/security/token/validator/RefreshTokenValidator.html[RefreshTokenValidator]. https://micronaut-projects.github.io/micronaut-security/snapshot/api/io/micronaut/security/token/refresh/RefreshTokenPersistence.html[RefreshTokenPersistence]. We will deal with the latter in the next section. For the generator and validator, Micronaut Security ships with  https://micronaut-projects.github.io/micronaut-security/snapshot/api/io/micronaut/security/token/jwt/generator/SignedRefreshTokenGenerator.html[SignedRefreshTokenGenerator]. It creates and verifies a JWS (JSON web signature) encoded object whose payload is a UUID with a hash-based message authentication code (HMAC). You need to provide secret to use `SignedRefreshTokenGenerator` which implements both `RefreshTokenGenerator` and `REfreshTokenValidator`.

Create a test to verify the login endpoint responds both access and refresh token:

[source,groovy]
.src/test/groovy/example/micronaut/LoginIncludesRefreshTokenSpec.groovy
----
include::{sourceDir}/src/test/groovy/example/micronaut/LoginIncludesRefreshTokenSpec.groovy[]
----

<1> A refresh token is returned.
